language: node_js
node_js:
  - 7
script: npm install
deploy:
- provider: azure_web_apps
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: fitobackend
  slot: fitobackend
  verbose: true
  on:
    branch: azure-teste