language: node_js
node_js:
  - 8.16.1
script:
  - "npm run lint"
  - "npm run test"

deploy:
  provider: heroku
  api_key:
    secure: "39904cb1-48ad-4856-80fc-2503edd3bed3"
  app: teste-travis-node
  on:
    repo: joberthrogers18/integration-continous-node
    branch: travis