language: node_js
node_js:
  - 7
script: npm install
deploy:
- provider: azure_web_apps
  username: fitologia
  password: j23231215
  site: fitobackend
  slot: fitobackend
  verbose: true
  on:
    branch: azure-teste